### ISSUE TITLE
After updating to 1.16 and also in the ne wersion the Channel Topic isn't updating anymore.

### ISSUE THREAD

**Issue by mihionmc** [ErdbeerbaerLP/Discord-Chat-Integration#180]
**The topic stays unchanged...**
-

**informe regarding players online uptime and so on**
-

**Steps to reproduce**
- 
- 

**Version**
-
- [ ] 1.12
- [x ] 1.16

**Platform**
-
- [x ] Forge
- [ ] Spigot

Mod version: 

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
This feature no longer exists due to new Discord limitations
(2 channel topic updates per 10 minutes)

**Comment by mihionmc** [comment]
I actually think that it is funny because this isn't a problem on my Papermc version so it can not a "new Discord limitation". But I have opened a new issue on the server crash experience on Direwolf10 v. 1.4.1

**Comment by ErdbeerbaerLP** [comment]
I removed that feature way before this was available for spigot. (Spigot support was added pretty recently)

I removed it because, in my opinion, this feature is pretty useless as it can only update every 10 minutes (opposed to every two seconds) and can freeze server start if the restart is too quick.

Commit where I removed the last piece of code of that feature from 1.15 code:
https://github.com/ErdbeerbaerLP/Discord-Chat-Integration/commit/df98c01a41d6052516f368ea617902b29840bad4#diff-9ec93106ae693538cef06f7abefbd3102d3e63e45041671cff60092044fb70daL57
